### ISSUE TITLE
не работает /profile/search на AWS

### ISSUE THREAD

**Issue by ak239** [mesto-co/core#75]
knex / postgresql не любят `array_to_string(json, unknown)` в AWS окружении.

```
POST profile/search error error: select "User"."id", "fullName", "username", "imagePath", "location", "about", "role", "skills", "status" from "User" where (("fullName" ilike $1 or "username" ilike $2 or "location" ilike $3 or "about" ilike $4 or "role" ilike $5 or array_to_string(skills, ',') ilike $6)) and "status" = $7 order by "createdAt" asc limit $8 - function array_to_string(json, unknown) does not exist
    at Parser.parseErrorMessage (/var/task/node_modules/pg-protocol/dist/parser.js:278:15)
    at Parser.handlePacket (/var/task/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/var/task/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/var/task/node_modules/pg-protocol/dist/index.js:10:42)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:483:12)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23) {
```

**Comment by ak239** [comment]
накатывал миграции на базу вручную, а не с помощью скрипта - не накатил обновление колонки skills - поправил в проде, проверил, что при накате вручную все работает.
