### ISSUE TITLE
PUT v1/user/ отдает 400

### ISSUE THREAD

**Issue by ak239** [mesto-co/core#76]
Возврщает 400.
```
curl 'https://api.mesto.co/v1/user/' \
  -X 'PUT' \
  -H 'authority: api.mesto.co' \
  -H 'pragma: no-cache' \
  -H 'cache-control: no-cache' \
  -H 'accept: application/json, text/plain, */*' \
  -H 'authorization: Bearer ...' \
  -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36' \
  -H 'content-type: application/json;charset=UTF-8' \
  -H 'origin: https://app.mesto.co' \
  -H 'sec-fetch-site: same-site' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-dest: empty' \
  -H 'referer: https://app.mesto.co/' \
  -H 'accept-language: en-US,en;q=0.9,ru-RU;q=0.8,ru;q=0.7' \
  --data-binary $'{"isFriend":false,"contacts":[{"title":"openland","url":"https://openland.com/LOaDEWDjrbt1Qq7EZwXQhY6j61"}],"id":"defd12ac-9876-4077-a2b7-5a9d240b2c14","fullName":"Алексей","username":null,"email":"ak239spb@gmail.com","imagePath":"https://ucarecdn.com/a517adbd-3700-4505-9986-c6566bc18008/","location":"","about":"Привет\u0021","skills":null,"status":"approved","RqUid":"7e26b129-f6f5-496a-808a-1f0f4dd020cb"}' \
  --compressed
```

**Comment by ak239** [comment]
```
INFO	error: update "User" set "about" = $1, "location" = $2, "role" = $3, "fullName" = $4, "skills" = $5, "imagePath" = $6 where "id" = $7 - invalid input syntax for type json
    at Parser.parseErrorMessage (/var/task/node_modules/pg-protocol/dist/parser.js:278:15)
    at Parser.handlePacket (/var/task/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/var/task/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/var/task/node_modules/pg-protocol/dist/index.js:10:42)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:483:12)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23) {
```

**Comment by ak239** [comment]
Фронтенд при редактировании пустого профиля шлет немного нулей, оба поля опциональные - если для них нет значений - они не должны отправляться.

@evgeniy-logvinov @icekhab 

```
skills: null
username: null
```
